import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Roboto, Poppins } from "next/font/google";
import "./globals.css";

/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); */

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500"]
})

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: []
})

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500"]

})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
